### ISSUE TITLE
 Error inflating class com.facebook.drawee.view.SimpleDraweeView

### ISSUE THREAD

**Issue by mcxinyu** [bboylin/UniversalToast#23]
`    android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.facebook.drawee.view.SimpleDraweeView
        at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at xyz.bboylin.universialtoast.SystemToast.makeText(SystemToast.java:75)
        at xyz.bboylin.universialtoast.UniversalToast.makeText(UniversalToast.java:55)`

请问这种是什么问题呢？
我的依赖里面也引入了
`    implementation 'com.facebook.fresco:fresco:1.10.0'
    implementation 'com.facebook.fresco:animated-gif:1.10.0'`

**Comment by bboylin** [comment]
fresco需要初始化。
