### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by zhulujiang** [bboylin/UniversalToast#24]
android.view.WindowLeaked: Activity com.gxkeji.obk.WelcomeActivity has leaked window android.widget.LinearLayout{d141a60 V.E...... ......ID 0,0-196,111} that was originally added here
                                                    at android.view.ViewRootImpl.<init>(ViewRootImpl.java:422)
                                                    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
                                                    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
                                                    at com.gxkeji.obk.base.toast.CustomToast.show(CustomToast.java:174)
                                                    at com.gxkeji.obk.tools.GlobalTools.showToastCenter(GlobalTools.java:302)
                                                    at com.gxkeji.obk.WelcomeActivity.jumpActivity(WelcomeActivity.java:91)

我的代码是
   UniversalToast.makeText(context, hint, UniversalToast.LENGTH_SHORT, UniversalToast.UNIVERSAL)
                .setGravity(Gravity.TOP
                        , 0, GlobalTools.getInstance().Dp2Px(context,distance))
//                                .setIcon(R.drawable.ic_done_white_24dp)
                .show();
 startActivity(new Intent(base, LoginActivity.class));
   finish();

**Comment by zhulujiang** [comment]
那个上下文我用的是 activity

**Comment by bboylin** [comment]
context传的activity是不是和finish()的activity不一致？

**Comment by ShengjieGeng** [comment]
![image](https://user-images.githubusercontent.com/18364968/54593027-8af6e000-4a68-11e9-89b6-fc9697cf25bc.png)
这个什么意思呢？
