### ISSUE TITLE
华为关闭通知后无法弹出toast

### ISSUE THREAD

**Issue by fansangg** [bboylin/UniversalToast#28]
华为手机
系统为android 8.0

**Comment by fansangg** [comment]
2019-03-29 16:17:42.791 com.meimeng.eshop E/TAG: 1SystemToast
2019-03-29 16:17:42.804 ? E/NotificationService: Suppressing toast from package com.meimeng.eshop by user request.
2019-03-29 16:17:42.942 ? E/HsmCoreServiceImpl: onTransact in code is: 103
2019-03-29 16:17:43.334 ? E/WindowManager: win=Window{5070462 u0 com.meimeng.eshop/com.meimeng.eshop.ui.activity.HomeActivity} destroySurfaces: appStopped=true win.mWindowRemovalAllowed=false win.mRemoveOnExit=false

**Comment by fansangg** [comment]
使用模拟器测试，报错
 Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@e8fcb2e -- permission denied for window type 2038
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:789)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at xyz.bboylin.universialtoast.CustomToast.show(CustomToast.java:183)
        at xyz.bboylin.universialtoast.CustomToast.showError(CustomToast.java:211)
