### ISSUE TITLE
在小米手机上运行,所有可点击Toast都崩溃

### ISSUE THREAD

**Issue by appdev** [bboylin/UniversalToast#8]
手机 MIX2
系统: Android 8.0
日志:
```
Process: xyz.bboylin.universaltoast, PID: 1999
                                                                          android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@2a4e321 -- permission denied for window type 2002
                                                                              at android.view.ViewRootImpl.setView(ViewRootImpl.java:809)
                                                                              at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:359)
                                                                              at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                                              at xyz.bboylin.universialtoast.UniversalToast.show(UniversalToast.java:273)
                                                                              at xyz.bboylin.universialtoast.UniversalToast.showSuccess(UniversalToast.java:297)
                                                                              at xyz.bboylin.demo.MainActivity$2.onItemClick(MainActivity.java:76)
                                                                              at android.widget.AdapterView.performItemClick(AdapterView.java:318)
                                                                              at android.widget.AbsListView.performItemClick(AbsListView.java:1188)
                                                                              at android.widget.AbsListView$PerformClick.run(AbsListView.java:3172)
                                                                              at android.widget.AbsListView$3.run(AbsListView.java:4153)
                                                                              at android.os.Handler.handleCallback(Handler.java:789)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                              at android.os.Looper.loop(Looper.java:164)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6665)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```

**Comment by appdev** [comment]
看了一下其他issue 说是权限问题,给了权限也不行~~

**Comment by bboylin** [comment]
请pull下最新代码再试下~之前忘记适配8.0了。

**Comment by bboylin** [comment]
我自己测试没问题了，V1.0.4

**Comment by appdev** [comment]
我试了一下，正常了感谢
